import Navbar from "@/components/NavBar";
import "../globals.css";
import { Montserrat } from "next/font/google";
import QueryProvider from "@/Layout/Provider";

export const metadata = {
  title: "Connect Wave",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <QueryProvider Children={<Navbar />} />
        {children}
      </body>
    </html>
  );
}
