import Navbar from "@/components/NavBar";
import "../globals.css";
import { Montserrat } from "next/font/google";
import LeftSideBar from "@/components/LeftSideBar";
import RightSideBar from "@/components/RightSideBar";

export const metadata = {
  title: "Connect Wave",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <>
          <Navbar />
          <div className="flex items-start  bg-gray-100 w-full py-[2%] px-[5%] justify-between">
            <LeftSideBar />
            {children}
            <RightSideBar />
          </div>
        </>
      </body>
    </html>
  );
}
