import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Connect Wave",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={montserrat.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
